### ISSUE TITLE
ViewPager/TabLayout functionality

### ISSUE THREAD

**Issue by pedromalta** [faruktoptas/FancyShowCaseView#157]
Would like to suggest/ask how to add a ViewPager + TabLayout (with small dots on the bottom) funcionality at the ShowCaseQueue, so users can go back and forward on the ShowCases.

If I would fork and implement it where would you suggest to start?

**Comment by faruktoptas** [comment]
Hi @pedromalta 
You can do by using custom views partially. But during the transition from one to another show case you will see exit then enter animations. Animations will prevent you to create this behavior. If you disable animations you can do it with next/prev buttons by manually writing your own queue(Because currently going to previous show case is not supported). But there is still a problem during transition. There will be a flashing effect because of removing and re-adding the show case to the root view.

Multiple show case instances can't solve this problem easily. But you can focus on multiple focused views. It should be something like that:

```kotlin
FancyShowCaseView.Builder(this)
    .focusOnMultiple(listOf(view1, view2, view3))
    .titles(lisfOf(title1, title2, title3))
    .build()
    .show()
```

But this is not enough. There should be prev/next buttons somewhere on the screen. And must be totally customizable. It is not easy to create a generic solution with this way.

Another option is compound view with focusing capability. So users can customize it as they wish. But this way will make it difficult to implement. Because steps will be like:
* Create an xml layout
* Add show case to the root of the xml
* Add your own controls (prev/next or whatever else)
* Inflate and add to root view of Activity
* Handle animations etc.

**Comment by pedromalta** [comment]
Huum ok, thanks. Yeap, upon trying to implement it I faced what you said. I figured it out with custom views and behaviors calling forward and backward. it ended up quite nicely thanks!

**Comment by pravind-hp** [comment]
@pedromalta Can you please elaborate more your solution with an example? @faruktoptas focusOnMultiple method not there in library.
