### ISSUE TITLE
Conver internal classes to "internal class"

### ISSUE THREAD

**Issue by faruktoptas** [faruktoptas/FancyShowCaseView#162]
Classes to be converted:
* FancyImageView
* Calculator

**Comment by YuetChan** [comment]
Hi I would like to working on this issue. Thank you

**Comment by faruktoptas** [comment]
Thanks PRs welcome :)

**Comment by YuetChan** [comment]
Do I just need to add internal keyword to both class Calculator in Calculator.kt and class FancyImageView in FancyImageView.kt? Do I have to edit any other file? I would appreciate your hel and feedback.

**Comment by YuetChan** [comment]
After I add internal keyword to the FancyImageView, the FancyShowCaseViewTest shows compiler error.
Since FancyImageView becomes internal in me.toptas.fancyshowcase, FancyShowCaseViewTest cannot access FancyImageView.

**Comment by YuetChan** [comment]
Thanks for the advise! 
After I google search on @VisibleForTesting, it seems like @VisibleForTesting does not actually change the viability of a class/function. If a class is internal/private/public, its visibility is internal/private/public. Adding @VisibleForTesting will provide message when class/function is used in production code.
Do I consider adding @VisibleForTesting(otherwise = VisbleForTesting.PACKAGE_PRIVATE) to both FancyImageView and Calculator?l instead?

**Comment by faruktoptas** [comment]
I think the best way is moving the tests under library folder. Currently tests are running under app module.

**Comment by YuetChan** [comment]
Do you mean moving the tests from app modules to fancyshowcaseview module?

**Comment by faruktoptas** [comment]
Yes. But it should be another task.

**Comment by YuetChan** [comment]
In summary, to convert internal class to "internal class", internal need to be added to FancyImageView and Calculator . After adding internal to FancyImageView and Calculator, FancyShowCaseViewTest need to be moved under fancyshowcaseview module.  Moving FancyShowCaseViewTest under fancyshowcaseview module should be another task.
Please correct me if I misunderstand the issue. Thank you.

**Comment by faruktoptas** [comment]
After this investigation the scope is changed a bit. 
* `FancyImageView` should be internal and 
* `DISABLE_ANIMATIONS_FOR_TESTING` will be moved under `Calculator`.
