### ISSUE TITLE
Add onclicklistener on focus view

### ISSUE THREAD

**Issue by gcrescent** [faruktoptas/FancyShowCaseView#40]
I want user can click the view the showcase is focusing. Is that possible?

**Comment by faruktoptas** [comment]
Yes it is possible by adding `closeOnTouch(false)` to builder params.

```
new FancyShowCaseView.Builder(this)
        .focusOn(mButton)
        .title("Focus a view")
        .closeOnTouch(false)
        .build()
        .show();
```

If you want to hide FancyShowCaseView when you click the focused view. You can use:

```
if (FancyShowCaseView.isVisible(this)){
    FancyShowCaseView.hideCurrent(this);
}
```

**Comment by gcrescent** [comment]
But I need the closeOnTouch behaviour too. I don't want to force user to click the focused view, but if they clicked on it, they will trigger the view onClick event

**Comment by faruktoptas** [comment]
You want 2 different click behaviours on a single view. This is possible with a tricky workaround. 
* Add a custom view should into FancyShowCaseView.
* Define a touch listener and get the position of touch. 
* If position is in the focused circle, perform click otherwise hide FancyShowCaseView. 

Focus position is not public yet. But there is an open pull request #31 about this.
You should calculate the focus position manually. [Calculator.java](https://github.com/faruktoptas/FancyShowCaseView/blob/master/library/src/main/java/me/toptas/fancyshowcase/Calculator.java) may help you about calculations.
