### ISSUE TITLE
Click on view in focus

### ISSUE THREAD

**Issue by nagot21** [faruktoptas/FancyShowCaseView#46]
Hey guys, quick question.

Is it possible to make only the target view (.focusOn) clickable even if .closeOnTouch is false?

Thanks!

**Comment by faruktoptas** [comment]
@nagot21 It is not supported yet by the library. But you can use a workaround. Get the touch position if position is in focused area focused view handles the click otherwise FancyShowCaseView handles the click (or manually call hide() method). Focus position is calculated in https://github.com/faruktoptas/FancyShowCaseView/blob/master/library/src/main/java/me/toptas/fancyshowcase/Calculator.java 

There is also an open issue #8 for accessing calculated values publicly.

**Comment by nagot21** [comment]
@faruktoptas Cool bro, thanks for that!

**Comment by faruktoptas** [comment]
You welcome @nagot21 
We should add something like  `enableTouchOnFocusedView` to builder params. 
Do you want to create a pull request to add this feature :) 
I will close this issue when this feature is implemented.

**Comment by andyb129** [comment]
Just added a pull request for this. hope is all looks OK :-)

**Comment by faruktoptas** [comment]
Thanks @andyb129 :) I will check it asap.

**Comment by faruktoptas** [comment]
@andyb129 I changed the touch logic a bit :)
Because the issue was making focused view clickable while FancyShowCaseView is visible.
Fixed with #76

**Comment by andyb129** [comment]
ok nice one. Looks good 👍
